### PR TITLE
update french translation

### PR DESCRIPTION
**Pull request by romainhk**
Hi !
I just updated the french tanslation of new menu items and game manual. If you want to merge this ;)

### CODE REVIEW

**Comment by TobiasBielefeld** [comment]
very friendly, thanks :D

**Comment by romainhk** [comment]
You're welcome ;)

**Comment by TobiasBielefeld** [comment]
Hey i have 2 new strings, could you tell me if the following translations are okay?

Close game => Fermer le jeu
Main Menu => Menu principal

**Comment by romainhk** [comment]
It's exactly that ! ;)

**Comment by TobiasBielefeld** [comment]
perfect, thanks :D

**Pull request merged**
