### PR TITLE
Fixing Finnish translations

### PR DESCRIPTION
**Pull request by winjar**

### CODE REVIEW

**Comment by TobiasBielefeld** [comment]
thank you very much :)

**Comment by TobiasBielefeld** [comment]
Hey i have 2 new strings, could you tell me if the following translations are okay?

Close game => Sulje peli
Main Menu => Päävalikko

**Comment by winjar** [comment]
Yes, both of them are okay.

**Comment by TobiasBielefeld** [comment]
good, thanks :D

**Pull request merged**
