### PR TITLE
french translation

### PR DESCRIPTION
**Pull request by romainhk**
Just finished a french translation :)

btw, I really like this game since found it on fdroid. Good job ;)

### CODE REVIEW

**Comment by TobiasBielefeld** [comment]
Thank you very much for the translation and also for the compliment :D I'll add it to a new release today

**Comment by romainhk** [comment]
You're welcome :)

**Comment by TobiasBielefeld** [comment]
Hey i added some new text strings to the files array.xml, strings-about and strings-settings, i would be glad if you could translate them too :) Currently the English versions of the strings are in the fr files.

**Comment by romainhk** [comment]
Hi, I'm quite busy this days, but i will do that as soon as it became calmer ;) Next week I hope !

**Pull request merged**
