### PR TITLE
updated translations (Polish and Esperanto)

### PR DESCRIPTION
**Pull request by verdulo**
What is the meaning of "deal correct sequences" - it means sequences possible to win, not truly random, yes?

### CODE REVIEW

**Comment by TobiasBielefeld** [comment]
Thanks for the translations!

well "deal correct sequences" will put all cards on the tableau, one stack for each family,  in ascending order from king to ace. So its like the end position. It's not shuffling in a way to make a win possible :)

And I see that some of the Polish translations were correct, should I continue using the online translator?

**Comment by verdulo** [comment]
I understand, it's developer option, but how to understand the text "dialog_mix_cards_text" ("expect correct sequences and cards on tableau")?

You can continue using online translator, the most important to me is, that new strings be marked in some way. Have you thought about using online translation service, such as transifex, or weblate?

**Comment by TobiasBielefeld** [comment]
In that context it should mean all cards which you have placed in ascending/descending (depends on the game) order on the tableau, eg a sequence of "4, 3, 2". So they don't get mixed too. Otherwise the re-deal option would do nearly the same thing. The other part is "and cards on the foundation", not tableau :)

And thanks for the site suggestion! I'll look into weblate. The other site isn't free to use.

**Comment by TobiasBielefeld** [comment]
I put my project now an online translation service: I chose POEditor for it :)
If you want to help there in the future, click here: https://poeditor.com/join/project/PYX4vcwTjA

**Pull request merged**
